### PR TITLE
Update copyright year & some tweaks for requests

### PR DESCRIPTION
**Pull request by mariacarmina**
- updated copyright year
- corrected header typo
- added retries for request session

### CODE REVIEW

**Review by alexcos20 — APPROVED** [review]

**Comment by alexcos20** [comment]
we can merge it once we have a description of the testing method

**Comment by mariacarmina** [comment]
Tested on local setup with a script implemented with ocean-lib and here is the output.

**Output**
```console
signing message with nonce 1678209690.409229: 0x529043886F21D9bc1AE0feDb751e34265a246e47did:op:06c3674cbef465e643770ec10023150ff20a1e1c91d2116074217e6812c192c4, account=0x529043886F21D9bc1AE0feDb751e34265a246e47
INFO:ocean_lib.data_provider.data_service_provider:invoke start compute endpoint with this url: {'dataset': {'documentId': 'did:op:06c3674cbef465e643770ec10023150ff20a1e1c91d2116074217e6812c192c4', 'serviceId': '2', 'transferTxId': '0xa05c58a4d80774e81444ab7dee6c5337f5fe772269a5cc384229553455476fde'}, 'environment': 'ocean-compute', 'algorithm': {'documentId': 'did:op:7a35e79a9f36afe261b957d1391eefdde8f57ad43b8b3e991af3316017e3eabe', 'serviceId': '0', 'transferTxId': '0x8a065c011630e0183c59e6234b7705c6cac976326432dad72ac05a71e997e255'}, 'signature': '0x6187f88f106c71f870d2ad24db39713b989a3f888350ee7b29e3db4bae8d207b0975aae061dd0c2f660644642b9884e124ddda910da932faa1c36d13a7008b6501', 'nonce': '1678209690.409229', 'consumerAddress': '0x529043886F21D9bc1AE0feDb751e34265a246e47', 'additionalInputs': []}
Started compute job with id: b67850a40cad4719a933c1150cd9fd11
```
**Script**

```python
import os

from ocean_lib.web3_internal.utils import connect_to_network

connect_to_network("development")

from ocean_lib.example_config import get_config_dict
from ocean_lib.ocean.ocean import Ocean

config = get_config_dict("development")
ocean = Ocean(config)

OCEAN = ocean.OCEAN_token
from ocean_lib.ocean.mint_fake_ocean import mint_fake_OCEAN
mint_fake_OCEAN(config)

# Create Alice's wallet
import os
from brownie.network import accounts
accounts.clear()

alice_private_key = os.getenv("TEST_PRIVATE_KEY1")
alice = accounts.add(alice_private_key)
assert alice.balance() > 0, "Alice needs ETH"
assert OCEAN.balanceOf(alice) > 0, "Alice needs OCEAN"

# Create Bob's wallet. While some flows just use Alice wallet, it's simpler to do all here.
bob_private_key = os.getenv('TEST_PRIVATE_KEY2')
bob = accounts.add(bob_private_key)
assert bob.balance() > 0, "Bob needs ETH"
assert OCEAN.balanceOf(bob) > 0, "Bob needs OCEAN"

from ocean_lib.structures.file_objects import UrlFile
DATA_url_file = UrlFile(
    url="https://raw.githubusercontent.com/oceanprotocol/c2d-examples/main/branin_and_gpr/branin.arff"
)

name = "Branin dataset"
(DATA_data_nft, DATA_datatoken, DATA_ddo) = ocean.assets.create_url_asset(name, DATA_url_file.url, {"from": alice}, wait_for_aqua=True)
print(f"DATA_data_nft address = '{DATA_data_nft.address}'")
print(f"DATA_datatoken address = '{DATA_datatoken.address}'")


# Create and attach the Service
DATA_files = [DATA_url_file]

# Add service and update asset
DATA_ddo.create_compute_service(
    service_id="2",
    service_endpoint=ocean.config_dict["PROVIDER_URL"],
    datatoken_address=DATA_datatoken.address,
    files=DATA_files,
)

# Update the asset
DATA_ddo = ocean.assets.update(DATA_ddo, {"from": alice})

print(f"DATA_ddo did = '{DATA_ddo.did}'")

ALGO_url = "https://raw.githubusercontent.com/oceanprotocol/c2d-examples/main/branin_and_gpr/gpr.py"

name = "grp"
(ALGO_data_nft, ALGO_datatoken, ALGO_ddo) = ocean.assets.create_algo_asset(name, ALGO_url, {"from": alice}, wait_for_aqua=True)

print(f"ALGO_data_nft address = '{ALGO_data_nft.address}'")
print(f"ALGO_datatoken address = '{ALGO_datatoken.address}'")
print(f"ALGO_ddo did = '{ALGO_ddo.did}'")

compute_service = DATA_ddo.services[1]
compute_service.add_publisher_trusted_algorithm(ALGO_ddo)
DATA_ddo = ocean.assets.update(DATA_ddo, {"from": alice})

from ocean_lib.ocean.util import to_wei
DATA_datatoken.mint(bob, to_wei(5), {"from": alice})
ALGO_datatoken.mint(bob, to_wei(5), {"from": alice})

DATA_did = DATA_ddo.did
ALGO_did = ALGO_ddo.did

# Operate on updated and indexed assets
DATA_ddo = ocean.assets.resolve(DATA_did)
ALGO_ddo = ocean.assets.resolve(ALGO_did)

compute_service = DATA_ddo.services[1]
algo_service = ALGO_ddo.services[0]
free_c2d_env = ocean.compute.get_free_c2d_environment(compute_service.service_endpoint)

from datetime import datetime, timedelta
from ocean_lib.models.compute_input import ComputeInput

DATA_compute_input = ComputeInput(DATA_ddo, compute_service)
ALGO_compute_input = ComputeInput(ALGO_ddo, algo_service)

# Pay for dataset and algo for 1 day
datasets, algorithm = ocean.assets.pay_for_compute_service(
    datasets=[DATA_compute_input],
    algorithm_data=ALGO_compute_input,
    consume_market_order_fee_address=bob.address,
    tx_dict={"from": bob},
    compute_environment=free_c2d_env["id"],
    valid_until=int((datetime.utcnow() + timedelta(days=1)).timestamp()),
    consumer_address=free_c2d_env["consumerAddress"],
)
assert datasets, "pay for dataset unsuccessful"
assert algorithm, "pay for algorithm unsuccessful"

# Start compute job
job_id = ocean.compute.start(
    consumer_wallet=bob,
    dataset=datasets[0],
    compute_environment=free_c2d_env["id"],
    algorithm=algorithm,
)
print(f"Started compute job with id: {job_id}")
```
The last print was executed successfully as it is shown in the output.

**Further workaround**
I have tried to add directly here but it ran into dependency conflicts between ocean-lib and other operator-service packages. I'll continue implementing an integration test in a separate PR to avoid messing up and loading the code here.
I have created a test image on DockerHub and it seemed that it didn't affect/solve provider. We can consider that this PR is used  for enhancement and for code consistency.

**Comment by mihaisc** [comment]
@alexcos20 @mariacarmina can we merge this?

**Comment by mariacarmina** [comment]
> @alexcos20 @mariacarmina can we merge this?

There are also small changes on the request side, I added `max_retries` and tested. It shouldn't affect anything because when I tested, it worked.
cc @alexcos20

**Pull request closed without merging**
