### PR TITLE
Require auth for admin routes

### LINKED ISSUE #62: Require auth for admin routes
We have some routes in admin_services.py that should be protected.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #62  .

Changes proposed in this PR:

- added env var `ALLOWED_ADMINS`;
- for each admin route check the header of the request to see the `Admin` key;
- updated `Dockerfile`

### CODE REVIEW

**Comment by mariacarmina** [comment]
I have done port forwarding from 31000 on AWS to 8051 on my host and tested with Postman:
Screenshot from 2022-05-17 14-11-18

Screenshot from 2022-05-17 14-11-40


Screenshot from 2022-05-17 14-31-14

**Comment by mariacarmina** [comment]
That address is for `OPERATOR_ADDRESS` and it was set for testing purpose.

**Comment by mariacarmina** [comment]
Tested the script and this is the output
Screenshot from 2022-05-27 10-43-36

**Review by alexcos20 — APPROVED** [review]
we need to update the readmes for this

**Review by alexcos20 — APPROVED** [review]

**Comment by calina-c** [comment]
I think the integration currently fails because there is no authentication configured. I will fix it :)

**Pull request merged**
