### PR TITLE
Added script to test the compute routes

### LINKED ISSUE #60: Write a script to test the routes of the operator service
The existent tests are very old. Use them as inspiration but not rely on them.

### PR DESCRIPTION
**Pull request by mariacarmina**
Fixes #60  .

Changes proposed in this PR:

- test the compute service routes
NOTE: I will create a script as well for #63 to test that specific functionality

### CODE REVIEW

**Comment by mariacarmina** [comment]
Tested PR #63 (used the docker image of operator service from that PR) and worked as expected, it throws an error in op-service,
because the `ALLOWED_ADMINS` is not provided in order to initialize the psql instance. Provider didn't throw an error, because this feature of op-serv is not integrated yet (it doesn't wrap the error message yet). The error occurred when trying to access the `computeEnvironments` endpoint.
Op-serv logs:
Screenshot from 2022-05-25 16-20-49
Script logs:
Screenshot from 2022-05-25 16-21-59
Provider logs:
Screenshot from 2022-05-25 16-28-23

**Comment by mariacarmina** [comment]
Tested the script and no errors
Screenshot from 2022-05-26 19-43-29

**Comment by mariacarmina** [comment]
@alexcos20 we can integrate the scripts folder for testing process when PR #58 will be merged. I have reproduced that flow locally and those scripts (from this PR and from #63 ) are tested with that setup and it works fine.

**Comment by calina-c** [comment]
Repurposed in #71.

**Pull request closed without merging**
